### ISSUE TITLE
Franz restart requires Zoho login when 2FA active

### ISSUE THREAD

**Issue by ringods** [muhammaddadu/franz-recipe-zoho-mail#2]
I have 3 Zoho accounts set up as 3 services in Franz. One of these accounts has 2FA active. At every start of Franz, I need to relogin to the Zoho account which has 2FA active.

If I login in on that account with e.g. Firefox or Chrome and restart the browser, the credentials survive and I don't need to relogin. Can you get the same behaviour working for the Franz service?

**Comment by muhammaddadu** [comment]
This could be an issue with the Franz platform on how it handles local storage & cookies.
